# Generated by Django 4.2.23 on 2025-07-04 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип груза')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Статус доставки')),
            ],
        ),
        migrations.CreateModel(
            name='PackageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип упаковки')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Услуга')),
            ],
        ),
        migrations.CreateModel(
            name='TransportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Модель ТС')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата доставки')),
                ('transport_number', models.CharField(max_length=100, verbose_name='Номер ТС')),
                ('distance_km', models.PositiveIntegerField(verbose_name='Дистанция (км)')),
                ('cargo_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveries.cargotype', verbose_name='Тип груза')),
                ('package_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.packagetype', verbose_name='Тип упаковки')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.service', verbose_name='Услуга')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.deliverystatus', verbose_name='Статус доставки')),
                ('transport_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deliveries.transportmodel', verbose_name='Модель ТС')),
            ],
        ),
    ]
